"use client";

import { SiteHeader } from "@/components/header";
import { SiteFooter } from "@/components/footer";
import { useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { getUserInventory, UserInventoryItem, request, WasteToAssetResponse, WasteToAssetIdea } from "@/lib/api";

export default function WasteToAssetPage() {
    const [inventory, setInventory] = useState<UserInventoryItem[]>([]);
    const [loading, setLoading] = useState(true);
    const [selectedItems, setSelectedItems] = useState<Set<string>>(new Set());
    const [aiResponse, setAiResponse] = useState<WasteToAssetResponse | null>(null);
    const [aiLoading, setAiLoading] = useState(false);
    const [modalIdea, setModalIdea] = useState<WasteToAssetIdea | null>(null);
    const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

    const searchParams = useSearchParams();

    useEffect(() => {
        async function loadInventory() {
            try {
                const items = await getUserInventory();
                setInventory(items);

                // Handle URL params for auto-selection
                const itemsParam = searchParams.get('items');
                const autoGenerate = searchParams.get('autoGenerate') === 'true';

                if (itemsParam) {
                    const itemNames = itemsParam.split(',').map(name => name.trim());
                    const validNames = new Set<string>();

                    // Only select items that exist in the inventory
                    itemNames.forEach(name => {
                        if (items.some(item => item.itemName === name)) {
                            validNames.add(name);
                        }
                    });

                    if (validNames.size > 0) {
                        setSelectedItems(validNames);

                        // Auto-generate if requested
                        if (autoGenerate && !hasAutoGenerated) {
                            setHasAutoGenerated(true);
                            // Trigger generation after a small delay to ensure UI is ready
                            setTimeout(() => {
                                handleGenerateSuggestions(validNames);
                            }, 500);
                        }
                    }
                }
            } catch (error) {
                console.error("Failed to load inventory:", error);
            } finally {
                setLoading(false);
            }
        }

        loadInventory();
    }, [searchParams]);

    const handleToggleItem = (itemName: string) => {
        const newSelection = new Set(selectedItems);
        if (newSelection.has(itemName)) {
            newSelection.delete(itemName);
        } else {
            newSelection.add(itemName);
        }
        setSelectedItems(newSelection);
    };

    const handleGenerateSuggestions = async (itemsToGenerate?: Set<string>) => {
        const itemsSet = itemsToGenerate || selectedItems;
        if (itemsSet.size === 0) return;

        setAiLoading(true);
        setAiResponse(null);

        try {
            const response = await request<WasteToAssetResponse>("/api/waste-to-asset", {
                method: "POST",
                body: JSON.stringify({ itemNames: Array.from(itemsSet) }),
            });
            setAiResponse(response);
        } catch (error) {
            console.error("Failed to get AI suggestions:", error);
            setAiResponse({
                canCombine: true,
                recipeIdeas: [
                    {
                        title: "Error Occurred",
                        summary: "Could not generate suggestions",
                        details: error instanceof Error ? error.message : "Please try again later.",
                    },
                ],
                nonRecipeIdeas: [],
            });
        } finally {
            setAiLoading(false);
        }
    };

    const getIdeaEmoji = (index: number, isRecipe: boolean) => {
        if (isRecipe) {
            const recipeEmojis = ["🥗", "🍹", "🍰"];
            return recipeEmojis[index] || "🍴";
        }
        const nonRecipeEmojis = ["🌱", "♻️", "✨"];
        return nonRecipeEmojis[index] || "💡";
    };

    const IdeaCard = ({ idea, index, isRecipe }: { idea: WasteToAssetIdea; index: number; isRecipe: boolean }) => (
        <div className="bg-white rounded-xl border-2 border-slate-200 overflow-hidden hover:border-[#714B67]/50 transition-all hover:shadow-lg">
            <div className="p-6">
                <div className="text-4xl mb-4 text-center">{getIdeaEmoji(index, isRecipe)}</div>
                <h3 className="text-lg font-bold text-slate-900 mb-2 text-center min-h-[3.5rem] flex items-center justify-center">
                    {idea.title}
                </h3>
                <p className="text-sm text-slate-600 mb-4 text-center min-h-[2.5rem]">
                    {idea.summary}
                </p>
                <button
                    onClick={() => setModalIdea(idea)}
                    className="w-full py-2 px-4 bg-slate-100 text-slate-700 font-medium rounded-lg hover:bg-[#714B67] hover:text-white transition-all text-sm"
                >
                    View Details
                </button>
            </div>
        </div>
    );

    return (
        <div className="min-h-screen bg-[#BCEBD7] text-slate-900 font-sans">
            <div className="mx-auto flex min-h-screen max-w-7xl flex-col px-4 sm:px-6 lg:px-8 pt-24">
                <SiteHeader />

                <main className="flex-1 py-12">
                    <div className="max-w-6xl mx-auto">
                        <div className="text-center mb-12">
                            <h1 className="text-4xl font-bold text-[#714B67] mb-4">
                                Waste to Asset
                            </h1>
                            <p className="text-lg text-slate-600 max-w-2xl mx-auto">
                                Select items from your inventory to get creative, AI-powered suggestions for repurposing them.
                            </p>
                        </div>

                        {/* AI Analytics Features Navigation */}
                        <div className="mb-8 bg-gradient-to-r from-emerald-50 to-green-50 rounded-2xl border-2 border-emerald-200 p-6">
                            <h2 className="text-xl font-bold text-gray-900 mb-4 flex items-center gap-2">
                                <span>🤖</span>
                                <span>AI-Powered Waste Management Tools</span>
                            </h2>
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                <a
                                    href="/analytics"
                                    className="block bg-white rounded-xl border-2 border-emerald-300 p-6 hover:border-emerald-500 hover:shadow-lg transition-all group"
                                >
                                    <div className="flex items-start gap-4">
                                        <div className="text-4xl group-hover:scale-110 transition-transform">
                                            🎯
                                        </div>
                                        <div className="flex-1">
                                            <h3 className="text-lg font-bold text-gray-900 mb-2 group-hover:text-emerald-600 transition-colors">
                                                Expiration Risk Analysis
                                            </h3>
                                            <p className="text-sm text-gray-600 mb-3">
                                                AI predicts which items are most likely to expire based on consumption patterns, seasonality, and category risks.
                                            </p>
                                            <ul className="text-xs text-gray-500 space-y-1">
                                                <li>• Risk scores for all inventory items</li>
                                                <li>• FIFO + AI prioritized consumption list</li>
                                                <li>• Smart alerts for high-risk items</li>
                                            </ul>
                                            <div className="mt-4 text-emerald-600 font-semibold text-sm flex items-center gap-2 group-hover:gap-3 transition-all">
                                                View Risk Dashboard
                                                <span>→</span>
                                            </div>
                                        </div>
                                    </div>
                                </a>

                                <a
                                    href="/analytics"
                                    className="block bg-white rounded-xl border-2 border-purple-300 p-6 hover:border-purple-500 hover:shadow-lg transition-all group"
                                >
                                    <div className="flex items-start gap-4">
                                        <div className="text-4xl group-hover:scale-110 transition-transform">
                                            ♻️
                                        </div>
                                        <div className="flex-1">
                                            <h3 className="text-lg font-bold text-gray-900 mb-2 group-hover:text-purple-600 transition-colors">
                                                Waste Analytics & Insights
                                            </h3>
                                            <p className="text-sm text-gray-600 mb-3">
                                                Get personalized insights on waste patterns with weekly/monthly projections and community comparisons.
                                            </p>
                                            <ul className="text-xs text-gray-500 space-y-1">
                                                <li>• Waste estimates in grams & money</li>
                                                <li>• Community percentile ranking</li>
                                                <li>• AI-generated reduction strategies</li>
                                            </ul>
                                            <div className="mt-4 text-purple-600 font-semibold text-sm flex items-center gap-2 group-hover:gap-3 transition-all">
                                                View Waste Analytics
                                                <span>→</span>
                                            </div>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>

                        {/* Divider */}
                        <div className="flex items-center gap-4 mb-8">
                            <div className="flex-1 h-px bg-slate-300"></div>
                            <span className="text-sm font-semibold text-slate-500 uppercase tracking-wider">
                                AI Recipe & Repurpose Generator
                            </span>
                            <div className="flex-1 h-px bg-slate-300"></div>
                        </div>

                        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                            {/* Inventory List with Multi-Select */}
                            <div className="lg:col-span-1 bg-slate-50 rounded-2xl p-6 border border-slate-200 h-fit">
                                <div className="flex justify-between items-center mb-6">
                                    <h2 className="text-xl font-bold text-slate-900">Your Inventory</h2>
                                    {selectedItems.size > 0 && (
                                        <span className="text-xs bg-[#714B67] text-white px-2 py-1 rounded-full font-semibold">
                                            {selectedItems.size} selected
                                        </span>
                                    )}
                                </div>

                                {loading ? (
                                    <div className="text-center py-8 text-slate-500">Loading items...</div>
                                ) : inventory.length === 0 ? (
                                    <div className="text-center py-8 text-slate-500">No items found.</div>
                                ) : (
                                    <>
                                        <div className="space-y-3 max-h-[500px] overflow-y-auto pr-2 custom-scrollbar mb-4">
                                            {inventory.map((item) => (
                                                <label
                                                    key={item.id}
                                                    className={`flex items-center gap-3 p-4 rounded-xl cursor-pointer transition-all border ${selectedItems.has(item.itemName)
                                                        ? 'bg-white border-[#714B67] shadow-md ring-1 ring-[#714B67]'
                                                        : 'bg-white border-slate-200 hover:border-[#714B67]/50 hover:shadow-sm'
                                                        }`}
                                                >
                                                    <input
                                                        type="checkbox"
                                                        checked={selectedItems.has(item.itemName)}
                                                        onChange={() => handleToggleItem(item.itemName)}
                                                        className="w-5 h-5 rounded border-2 border-slate-300 text-[#714B67] focus:ring-2 focus:ring-[#714B67]/20 cursor-pointer"
                                                    />
                                                    <div className="flex-1">
                                                        <div className="flex justify-between items-center">
                                                            <span className="font-medium text-slate-900">{item.itemName}</span>
                                                            <span className="text-xs text-slate-500 bg-slate-100 px-2 py-1 rounded-full">
                                                                {item.category}
                                                            </span>
                                                        </div>
                                                        {item.expirationDate && (
                                                            <div className="mt-1 text-xs text-slate-500">
                                                                Expires: {new Date(item.expirationDate).toLocaleDateString()}
                                                            </div>
                                                        )}
                                                    </div>
                                                </label>
                                            ))}
                                        </div>

                                        <button
                                            onClick={() => handleGenerateSuggestions()}
                                            disabled={selectedItems.size === 0 || aiLoading}
                                            className="w-full py-3 px-4 bg-[#714B67] text-white font-semibold rounded-xl transition-all shadow-md hover:bg-[#5d3d55] disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:bg-[#714B67]"
                                        >
                                            {aiLoading ? "Generating..." : `Generate Ideas (${selectedItems.size})`}
                                        </button>
                                    </>
                                )}
                            </div>

                            {/* AI Result Area */}
                            <div className="lg:col-span-2">
                                {!aiResponse ? (
                                    <div className="bg-slate-50 rounded-2xl border border-slate-200 p-12 min-h-[500px] flex flex-col items-center justify-center text-center">
                                        <div className="w-20 h-20 bg-slate-200 rounded-full flex items-center justify-center mb-6 text-4xl">
                                            🌱
                                        </div>
                                        <h3 className="text-2xl font-semibold text-slate-900 mb-3">Select Items to Begin</h3>
                                        <p className="text-slate-500 max-w-md">
                                            Choose one or more items from your inventory, then click "Generate Ideas" to see creative ways to repurpose them.
                                        </p>
                                    </div>
                                ) : aiLoading ? (
                                    <div className="bg-white rounded-2xl border border-slate-200 p-12 min-h-[500px] flex flex-col items-center justify-center">
                                        <div className="relative mb-6">
                                            <div className="h-20 w-20 rounded-full border-4 border-slate-100 border-t-[#714B67] animate-spin"></div>
                                            <div className="absolute inset-0 flex items-center justify-center text-sm font-bold text-[#714B67]">AI</div>
                                        </div>
                                        <p className="text-slate-600 font-medium animate-pulse text-lg">
                                            Analyzing {selectedItems.size} item{selectedItems.size > 1 ? 's' : ''}...
                                        </p>
                                    </div>
                                ) : (
                                    <div className="space-y-8">
                                        {/* Compatibility Message */}
                                        {!aiResponse.canCombine && selectedItems.size > 1 && (
                                            <div className="bg-amber-50 border border-amber-200 rounded-xl p-4 flex items-start gap-3">
                                                <span className="text-2xl">⚠️</span>
                                                <div>
                                                    <h4 className="font-semibold text-amber-900 mb-1">Items Can't Be Combined</h4>
                                                    <p className="text-sm text-amber-800">
                                                        These items work better separately. Here are individual ideas for each:
                                                    </p>
                                                </div>
                                            </div>
                                        )}

                                        {/* Recipe Ideas Section */}
                                        {aiResponse.recipeIdeas && aiResponse.recipeIdeas.length > 0 && (
                                            <div>
                                                <h2 className="text-2xl font-bold text-slate-900 mb-4 flex items-center gap-2">
                                                    <span>🍽️</span>
                                                    <span>Recipe Ideas</span>
                                                </h2>
                                                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                                                    {aiResponse.recipeIdeas.slice(0, 3).map((idea, index) => (
                                                        <IdeaCard key={`recipe-${index}`} idea={idea} index={index} isRecipe={true} />
                                                    ))}
                                                </div>
                                            </div>
                                        )}

                                        {/* Non-Recipe Ideas Section */}
                                        {aiResponse.nonRecipeIdeas && aiResponse.nonRecipeIdeas.length > 0 && (
                                            <div>
                                                <h2 className="text-2xl font-bold text-slate-900 mb-4 flex items-center gap-2">
                                                    <span>🛠️</span>
                                                    <span>Other than Recipe</span>
                                                </h2>
                                                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                                                    {aiResponse.nonRecipeIdeas.slice(0, 3).map((idea, index) => (
                                                        <IdeaCard key={`non-recipe-${index}`} idea={idea} index={index} isRecipe={false} />
                                                    ))}
                                                </div>
                                            </div>
                                        )}

                                        {/* Generate Again Button */}
                                        <div className="flex justify-center pt-4">
                                            <button
                                                onClick={() => handleGenerateSuggestions()}
                                                disabled={aiLoading}
                                                className="py-3 px-8 bg-white border-2 border-[#714B67] text-[#714B67] font-semibold rounded-xl transition-all shadow-sm hover:bg-[#714B67] hover:text-white disabled:opacity-50 disabled:cursor-not-allowed"
                                            >
                                                🔄 Generate New Ideas
                                            </button>
                                        </div>
                                    </div>
                                )}
                            </div>
                        </div>
                    </div>
                </main>

                <SiteFooter />
            </div>

            {/* Modal for Idea Details */}
            {modalIdea && (
                <div
                    className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center p-4 z-50"
                    onClick={() => setModalIdea(null)}
                >
                    <div
                        className="bg-white rounded-2xl max-w-2xl w-full max-h-[80vh] overflow-y-auto shadow-2xl"
                        onClick={(e) => e.stopPropagation()}
                    >
                        <div className="sticky top-0 bg-white border-b border-slate-200 p-6 flex justify-between items-start">
                            <div>
                                <h2 className="text-2xl font-bold text-slate-900 mb-2">
                                    {modalIdea.title}
                                </h2>
                                <p className="text-slate-600">
                                    {modalIdea.summary}
                                </p>
                            </div>
                            <button
                                onClick={() => setModalIdea(null)}
                                className="text-slate-400 hover:text-slate-600 transition-colors p-2"
                            >
                                <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                                </svg>
                            </button>
                        </div>
                        <div className="p-6">
                            <h3 className="text-lg font-semibold text-slate-900 mb-3">Detailed Instructions</h3>
                            <p className="text-slate-700 leading-relaxed whitespace-pre-line">
                                {modalIdea.details}
                            </p>
                        </div>
                        <div className="sticky bottom-0 bg-slate-50 border-t border-slate-200 p-6">
                            <button
                                onClick={() => setModalIdea(null)}
                                className="w-full py-3 px-6 bg-[#714B67] text-white font-semibold rounded-xl hover:bg-[#5d3d55] transition-all"
                            >
                                Close
                            </button>
                        </div>
                    </div>
                </div>
            )}

            <style jsx global>{`
                .custom-scrollbar::-webkit-scrollbar {
                    width: 6px;
                }
                .custom-scrollbar::-webkit-scrollbar-track {
                    background: #f1f5f9;
                    border-radius: 10px;
                }
                .custom-scrollbar::-webkit-scrollbar-thumb {
                    background: #cbd5e1;
                    border-radius: 10px;
                }
                .custom-scrollbar::-webkit-scrollbar-thumb:hover {
                    background: #94a3b8;
                }
            `}</style>
        </div>
    );
}